# Basic
title: Koooyf
subtitle: Aragaki Yui is my wife
description: Share somthing intersting and ACM algorithm
#creator: <a href="http://onev.cat">@onevcat</a>

#url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
#nav:
#   - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 2632411923
    github: koooyf
    twitter: koooyf
    mail: kyf19970408@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
